# Generated by Django 5.0.1 on 2024-01-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsnippets',
            name='title',
        ),
        migrations.AddField(
            model_name='textsnippets',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
